In [0]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score

In [0]:
train_path='train.csv'
test_path='testX.csv'
train=pd.read_csv(train_path)
print(train.shape)
train

(60000, 786)


Id  Label  1  2  3  4  5  6  ...  777  778  779  780  781  782  783  784
0      10000      4  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
1      10001      0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
2      10002      0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
3      10003      4  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
4      10004      1  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
...      ...    ... .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995  69995      3  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59996  69996      0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59997  69997      4  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59998  69998      0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59999  69999      2  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0

[60000 rows x 786 columns]

In [0]:
test=pd.read_csv(test_path)
test

Id  0  1  2  3  4  5  6  ...  776  777  778  779  780  781  782  783
0        0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
1        1  0  0  0  0  0  1  0  ...  130   76    0    0    0    0    0    0
2        2  0  0  0  0  0  0  0  ...    1    0    0    0    0    0    0    0
3        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
4        4  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
...    ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
9995  9995  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
9996  9996  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
9997  9997  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
9998  9998  0  0  0  1  0  0  0  ...  138   51    0    3    0    0    0    0
9999  9999  0  0  0  0  1  0  0  ...    0    0   76   47    0    0    0    0

[10000 rows x 785 columns]

In [0]:
X = train.iloc[:,2:]
i=100
#X = train.drop('Label',axis=1)#
X = train.iloc[:,2:]
Y = train.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

X

1  2  3  4  5  6  7  8  9  ...  776  777  778  779  780  781  782  783  784
0      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
1      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
2      0  0  0  0  0  0  0  0  1  ...    9    0    0    0    0    0    0    0    0
3      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
4      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
...   .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59996  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59997  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59998  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59999  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0

[60000 rows x 784 columns]

In [0]:
Y = train.iloc[:,1]
Y

0        4
1        0
2        0
3        4
4        1
        ..
59995    3
59996    0
59997    4
59998    0
59999    2
Name: Label, Length: 60000, dtype: int64

In [0]:
Y.shape

(60000,)

In [0]:
pca = PCA(n_components=50, random_state = 42)
X_train = pca.fit_transform(X_train)
X_test=pca.fit_transform(X_test)
testdata=pca.fit_transform(test)
print(X_train.shape)
print(X_test.shape)
print(testdata.shape)

(48000, 100)
(12000, 100)
(10000, 100)


In [0]:
from sklearn import svm
import sklearn.metrics as metrics
clf=svm.SVC(C=12,probability=True)
clf.fit(X_test,y_test)

SVC(C=12, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [0]:
trainset=train.iloc[:,2:]
testset=test.iloc[:,1:]
trainset

1  2  3  4  5  6  7  8  9  ...  776  777  778  779  780  781  782  783  784
0      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
1      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
2      0  0  0  0  0  0  0  0  1  ...    9    0    0    0    0    0    0    0    0
3      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
4      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
...   .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59996  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59997  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59998  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59999  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0

[60000 rows x 784 columns]

PCA + SVM C=12 kernel='rbf'


In [0]:
from sklearn.decomposition import PCA
X = train.iloc[:,2:]
Y = train.iloc[:,1]
pca_m=PCA(n_components=100)
pca_m.fit(X)
X_PCA=pca_m.transform(X)
testset_PCA=pca_m.transform(testset)

In [0]:
from sklearn import svm
clf=svm.SVC(C=12,kernel='rbf') 
clf.fit(X_PCA,Y.values.ravel())
y_pred=clf.predict(X_PCA)
print(metrics.accuracy_score(Y,y_pred))
#print('Training time is',(time.time()-s))
#s=time.time()
y_pred_svc_pca = clf.predict(testset_PCA)
output = pd.DataFrame({'Id': test.Id, 'Label': y_pred_svc_pca})
#output.to_csv('my_submission5.csv', index=False)
print("Your submission was successfully saved!")
output
#print('testing time is',(time.time()-s))



svc_f1 = metrics.f1_score(Y, y_pred, average= "weighted")
svc_accuracy = metrics.accuracy_score(Y, y_pred)
svc_cm = metrics.confusion_matrix(Y, y_pred)
print("-----------------SVM Report---------------")
print("F1 score: {}".format(svc_f1))
print("Accuracy score: {}".format(svc_accuracy))
print("Confusion matrix: \n", svc_cm)
print('Plotting confusion matrix')

from sklearn.metrics import recall_score
print('Sensitivity is',recall_score(Y, y_pred,average='micro'))
print('Recall is',recall_score(Y, y_pred,average='micro'))

from sklearn.metrics import precision_score
print('Precision score is',precision_score(Y, y_pred,average='micro'))


specificity1 = svc_cm[1,1]/(svc_cm[1,0]+svc_cm[1,1])
print('Specificity : ', specificity1)

0.9387
Your submission was successfully saved!
-----------------SVM Report---------------
F1 score: 0.9386440112501975
Accuracy score: 0.9387
Confusion matrix: 
 [[11618   290    61     0     6]
 [  320 11135   423   102     6]
 [  123   552 10855   390    74]
 [    5   131   435 11054   353]
 [    5    23    77   302 11660]]
Plotting confusion matrix
Sensitivity is 0.9387
Recall is 0.9387
Precision score is 0.9387
Specificity :  0.9720646006110869


In [0]:
from sklearn.metrics import mean_squared_error
print('MSE',mean_squared_error(Y, y_pred))
from sklearn.metrics import mean_absolute_error
print('MAE',mean_absolute_error(Y, y_pred))

MSE 0.09698333333333334
MAE 0.07245


In [0]:
import time
s=time.time()
X = train.iloc[:,2:]
Y = train.iloc[:,1]
clf=svm.SVC(C=12, kernel='rbf')
clf.fit(X,Y.values.ravel())
y_pred=clf.predict(X)
print(metrics.accuracy_score(Y,y_pred))
print('Training time is',(time.time()-s))
s=time.time()
y_pred_svc_pca = clf.predict(testset)
output = pd.DataFrame({'Id': test.Id, 'Label': y_pred_svc_pca})
#output.to_csv('my_submission5.csv', index=False)
print("Your submission was successfully saved!")
output
print('testing time is',(time.time()-s))
svc_f1 = metrics.f1_score(Y, y_pred, average= "weighted")
svc_accuracy = metrics.accuracy_score(Y, y_pred)
svc_cm = metrics.confusion_matrix(Y, y_pred)
print("-----------------SVM Report---------------")
print("F1 score: {}".format(svc_f1))
print("Accuracy score: {}".format(svc_accuracy))
print("Confusion matrix: \n", svc_cm)
print('Plotting confusion matrix')
specificity1 = svc_cm[1,1]/(svc_cm[1,0]+svc_cm[1,1])
print('Specificity : ', specificity1)
from sklearn.metrics import recall_score
print('Sensitivity is',recall_score(Y, y_pred,average='micro'))
print('Recall is',recall_score(Y, y_pred,average='micro'))

from sklearn.metrics import precision_score
print('Precision score is',precision_score(Y, y_pred,average='micro'))
specificity1 = svc_cm[1,1]/(svc_cm[1,0]+svc_cm[1,1])
print('Specificity : ', specificity1)
from sklearn.metrics import mean_squared_error
print('MSE',mean_squared_error(Y, y_pred))
from sklearn.metrics import mean_absolute_error
print('MAE',mean_absolute_error(Y, y_pred))

0.9705166666666667
Training time is 4065.404742002487
Your submission was successfully saved!
testing time is 297.25239658355713
-----------------SVM Report---------------
F1 score: 0.9704949390694684
Accuracy score: 0.9705166666666667
Confusion matrix: 
 [[11814   149    12     0     0]
 [  189 11607   165    25     0]
 [   40   288 11432   210    24]
 [    5    65   197 11509   202]
 [    1     2    41   154 11869]]
Plotting confusion matrix
Specificity :  0.9839776195320448
Sensitivity is 0.9705166666666667
Recall is 0.9705166666666667
Precision score is 0.9705166666666667
Specificity :  0.9839776195320448
MSE 0.04101666666666667
MAE 0.033216666666666665


In [0]:
from sklearn import svm
clf=svm.SVC(C=12,probability=True)
y_score=clf.fit(X_PCA,Y.values.ravel())
y_pred_svc_pca = clf.predict(testset_PCA)
output = pd.DataFrame({'Id': test.Id, 'Label': y_pred_svc_pca})
#output.to_csv('my_submission5.csv', index=False)
#print("Your submission was successfully saved!")
output

Id  Label
0        0      4
1        1      4
2        2      1
3        3      1
4        4      1
...    ...    ...
9995  9995      1
9996  9996      1
9997  9997      3
9998  9998      2
9999  9999      2

[10000 rows x 2 columns]

In [0]:
print("Train size:{}\nTest size:{}".format(train.shape, test.shape))

Train size:(60000, 786)
Test size:(10000, 785)


In [0]:
#examining Nan Values
train.isnull().any().sum()
test.isnull().any().sum()

0

In [0]:

train.Label.unique()

array([4, 0, 1, 2, 3])

In [0]:
train.head()

Id  Label  1  2  3  4  5  6  ...  777  778  779  780  781  782  783  784
0  10000      4  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
1  10001      0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
2  10002      0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
3  10003      4  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
4  10004      1  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0

[5 rows x 786 columns]

In [0]:
X = train.drop('Label',axis=1)#[:2]#drop id and label?
X
#Labels
y = train['Label']
y
print('shape of x is ',X.shape)
print('shape of y is ', y.shape)
print('shape of test data',test.shape)

shape of x is  (60000, 785)
shape of y is  (60000,)
shape of test data (10000, 785)


Knn with n_neighbours=1

In [0]:
import time
s=time.time()
X = train.iloc[:,2:]
Y = train.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42) #should i remove the test from here
clf = KNeighborsClassifier(n_neighbors=1)#,algorithm='auto',n_jobs=10)
clf.fit(X_train,y_train)
scores_list=[]
y_pred=clf.predict(X_test) #the test set should be used
#Store the accuracy of the model.
scores_list.append(metrics.accuracy_score(y_test,y_pred))
print(scores_list)
print('time taken is',(time.time()-s))
#predictions = clf.predict(test)
#output = pd.DataFrame({'Id': test.Id, 'Label': predictions})
#output

Knn with n_neighbours=15


In [0]:
import time
s=time.time()
X = train.iloc[:,2:]
Y = train.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42) #should i remove the test from here
clf = KNeighborsClassifier(n_neighbors=15)#,algorithm='auto',n_jobs=10)
clf.fit(X_train,y_train)
scores_list=[]
y_pred=clf.predict(X_test) #the test set should be used
#Store the accuracy of the model.
scores_list.append(metrics.accuracy_score(y_test,y_pred))
print(scores_list)
print('time taken is',(time.time()-s))
#predictions = clf.predict(test)
#output = pd.DataFrame({'Id': test.Id, 'Label': predictions})
#output

[0.8440833333333333]
time taken is 1011.7510423660278


Knn with n_neighbours=25


In [0]:
import time
s=time.time()
X = train.iloc[:,2:]
Y = train.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42) #should i remove the test from here
clf = KNeighborsClassifier(n_neighbors=25)#,algorithm='auto',n_jobs=10)
clf.fit(X_train,y_train)
scores_list=[]
y_pred=clf.predict(X_test) #the test set should be used
#Store the accuracy of the model.
scores_list.append(metrics.accuracy_score(y_test,y_pred))
print(scores_list)
print('time taken is',(time.time()-s))
#predictions = clf.predict(test)
#output = pd.DataFrame({'Id': test.Id, 'Label': predictions})
#output

More design choices for Random forest


In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
s=time.time()
num_trees = [5,10,50,150,200]
max_d=[3,5,10,None]
scores_list=[]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=42) 
for n in range (len(num_trees)):
    for m in range (len(max_d)):
        model = RandomForestClassifier(n_estimators=num_trees[n], max_depth=max_d[m], random_state=42)
        model.fit(X_train, y_train)
        results =cross_val_score(model, X=X_train, y=y_train,cv=10,scoring='accuracy')
        
        
        #y_pred=model.predict(X_test) #the test set should be used
#Store the accuracy of the model.
        #result=metrics.accuracy_score(y_test,y_pred)
        scores_list.append(results)
        print('for num_trees:',num_trees[n],' and depth: ',max_d[m],"---->",results.mean())
print(scores_list)
print('time taken for training is',(time.time()-s))
s=time.time()
predictions = model.predict(testset_PCA)
output = pd.DataFrame({'Id': test.Id, 'Label': predictions})
print('time taken for testing is',(time.time()-s))
output

for num_trees: 5  and depth:  3 ----> 0.5509375000000001
for num_trees: 5  and depth:  5 ----> 0.6477916666666667
for num_trees: 5  and depth:  10 ----> 0.7916041666666667
for num_trees: 5  and depth:  None ----> 0.8252291666666667
for num_trees: 10  and depth:  3 ----> 0.6014166666666667
for num_trees: 10  and depth:  5 ----> 0.6809791666666667
for num_trees: 10  and depth:  10 ----> 0.8056666666666666
for num_trees: 10  and depth:  None ----> 0.8486041666666667
for num_trees: 50  and depth:  3 ----> 0.6262500000000001
for num_trees: 50  and depth:  5 ----> 0.7161666666666667
for num_trees: 50  and depth:  10 ----> 0.8262708333333334
for num_trees: 50  and depth:  None ----> 0.8728958333333333
for num_trees: 150  and depth:  3 ----> 0.6395416666666667
for num_trees: 150  and depth:  5 ----> 0.7264583333333333
for num_trees: 150  and depth:  10 ----> 0.8266249999999999
for num_trees: 150  and depth:  None ----> 0.876125
for num_trees: 200  and depth:  3 ----> 0.6362500000000001
for num

Id  Label
0        0      3
1        1      4
2        2      0
3        3      1
4        4      2
...    ...    ...
9995  9995      3
9996  9996      1
9997  9997      3
9998  9998      2
9999  9999      2

[10000 rows x 2 columns]

Random forest with cross val score =10, max_depth=None, n_estimators=300

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
#num_trees = [5,10,50,150,200]
#max_d=[3,5,10,None]
scores_list=[]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
#for n in range (len(num_trees)):
#for m in range (len(max_d)):
model = RandomForestClassifier(n_estimators=300, max_depth= None,random_state=42)
model.fit(X_train, y_train)
results =cross_val_score(model, X=X_train, y=y_train,cv=10,scoring='accuracy')
        
        
        #y_pred=model.predict(X_test) #the test set should be used
#Store the accuracy of the model.
        #result=metrics.accuracy_score(y_test,y_pred)
scores_list.append(results)
#print('for num_trees:',num_trees[n],' and depth: ',max_d[m],"---->",results.mean())
print(results.mean())



0.8738958333333333


Random forest with  max_depth=None,n_estimators=200

In [0]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
model = RandomForestClassifier(n_estimators=200, max_depth=None, random_state=42)
model.fit(X_train, y_train)

scores_list=[]
y_pred=model.predict(X_test) #the test set should be used
#Store the accuracy of the model.
scores_list.append(metrics.accuracy_score(y_test,y_pred))
print(scores_list)


[0.8766666666666667]


Random forest with max_depth=None,n_estimators=250


In [0]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
model = RandomForestClassifier(n_estimators=250, max_depth=None, random_state=42)
model.fit(X_train, y_train)

scores_list=[]
y_pred=model.predict(X_test) #the test set should be used
#Store the accuracy of the model.
scores_list.append(metrics.accuracy_score(y_test,y_pred))
print(scores_list)


[0.8770833333333333]


Design choices for SVM

In [0]:
from sklearn import svm
from sklearn.model_selection import cross_val_score

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42) #splitting the data into test data(80%) train data␣
list=[]
C= [0.1, 0.5, 1, 2, 5, 10, 20, 50,70,90,100] # remove this
clf = svm.SVC(kernel='rbf',C=2500, random_state=42)
clf.fit(X_train,y_train)
scores = cross_val_score(clf, X_train, y_train,cv=10, scoring='accuracy') 
#print('for c =',C,' accuracy is ',scores*100,'%')
list.append(scores.mean()*100)
print(list)

for c = [0.1, 0.5, 1, 2, 5, 10, 20, 50, 70, 90, 100]  accuracy is  [68.25       69.66666667 67.875      68.3125     68.64583333 67.70833333
 68.16666667 67.29166667 67.75       67.875     ] %
[68.15416666666667]


GridSearchCV


In [0]:
X = train.drop('Label',axis=1)#[:2]#drop id and label?
X
#Labels
y = train['Label']
y

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
steps = [('scaler', StandardScaler()), ('SVM', SVC())]
from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps) # define the pipeline object
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=30, stratify=y)
parameteres = {'SVM__C':[0.001,0.1,10,100,10e5], 'SVM__gamma':[0.1,0.01]}
grid = GridSearchCV(pipeline, param_grid=parameteres, cv=5)
grid.fit(X_train, y_train)
print ("score = %3.2f" %(grid.score(X_test,y_test)))
print (grid.best_params_)

score = 0.86
{'SVM__C': 10, 'SVM__gamma': 0.1}


In [0]:
X = train.iloc[:,2:]
Y = train.iloc[:,1]
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

X

1  2  3  4  5  6  7  8  9  ...  776  777  778  779  780  781  782  783  784
0      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
1      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
2      0  0  0  0  0  0  0  0  1  ...    9    0    0    0    0    0    0    0    0
3      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
4      0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
...   .. .. .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59996  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59997  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59998  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
59999  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0

[60000 rows x 784 columns]

SVM Cross val score =50, C=12, kernel=rbf

In [0]:
from sklearn.model_selection import cross_val_score
scores_list=[]
from sklearn import svm
clf = svm.SVC(C=12,kernel='rbf', random_state=42)
clf.fit(X_train,y_train)
scores=cross_val_score(estimator=clf,X=X_train,y=y_train,cv=55,scoring='accuracy')
#y_pred=clf.predict(X_test)
scores_list.append(scores.mean())
print(scores_list)

[0.8934790542328612]


In [0]:
from sklearn import svm
scores_list=[]
#X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42) #splitting the data into test data(80%) train data␣
C= [0.1, 0.5, 1, 2, 5, 10, 20, 50,70,90,100]
clf = svm.SVC(C=12)
clf.fit(X_train,y_train)
#y_pred=clf.predict(X_test)
#scores_list.append(metrics.accuracy_score(y_test,y_pred))
scores = cross_val_score(clf, X_train, y_train,cv=10, scoring='accuracy') 
#print('for c =',C,' accuracy is ',scores*100,'%')
scores_list.append(scores.mean()*100)
#print(list)
print(scores_list)

In [0]:
from sklearn import svm
scores_list=[]
#X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42) #splitting the data into test data(80%) train data␣
C= [0.1, 0.5, 1, 2, 5, 10, 20, 50,70,90,100]
clf = svm.SVC(C=12, kernel='rbf')
clf.fit(X_train,y_train)
#y_pred=clf.predict(X_test)
#scores_list.append(metrics.accuracy_score(y_test,y_pred))
scores = cross_val_score(clf, X_train, y_train,cv=10, scoring='accuracy') 
#print('for c =',C,' accuracy is ',scores*100,'%')
scores_list.append(scores.mean()*100)
#print(list)
print(scores_list)

In [0]:
X.shape

(60000, 784)

In [0]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=250, max_depth=None, random_state=42)
model.fit(X_train, y_train)

scores_list=[]
y_pred=model.predict(X_test) #the test set should be used
#Store the accuracy of the model.
scores_list.append(metrics.accuracy_score(y_test,y_pred))
print(scores_list)


[0.8479166666666667]


In [0]:
from sklearn.model_selection import cross_val_score
X = train.iloc[:,2:]
y = train.iloc[:,1]
scores_list=[]
from sklearn import svm
clf = svm.SVC(C=12, random_state=42)
clf.fit(X,y)
scores=cross_val_score(estimator=clf,X=X,y=y,cv=10,scoring='accuracy')
#y_pred=clf.predict(X_test)
scores_list.append(scores.mean())
print(scores_list)

In [0]:
pca = PCA(n_components=50, random_state = 42)
X_train_proj = pca.fit_transform(X_train)
X_test_proj=pca.fit_transform(X_test)
testdata=pca.fit_transform(test)
print(X_train.shape)
print(X_test.shape)
print(testdata.shape)

(48000, 784)
(12000, 784)
(10000, 50)


XGBClassifier

In [0]:
import time
from xgboost import XGBClassifier
from sklearn import svm
from sklearn.ensemble import VotingClassifier


In [0]:
vot_clf_train_start = time.time()

xgb_clf_ens = XGBClassifier(n_estimators=400,max_depth=250,random_state=42)

svm_clf_ens = svm.SVC(kernel = 'linear', C = 12, random_state=42)

voting_clf = VotingClassifier(

    estimators=[('xgb', xgb_clf_ens),('svm', svm_clf_ens)],

    voting='hard')

voting_clf.fit(X_train_proj, y_train)

vot_y_pred = voting_clf.predict(X_test_proj)

vot_clf_end_train = time.time()

acc_voting = metrics.accuracy_score(y_test,vot_y_pred)*100

acc_voting

print('training time is',(vot_clf_end_train - vot_clf_train_start ))



